#!/bin/sh
#
# Generate an SML file that contains HTML4 CSS style definitions.
#
# usage: gen-sml.sh <style.css> <output.sml>
#

CSS_FILE=$1
SML_FILE=$2
SML_BASE=$(basename $SML_FILE)

cat - > $SML_FILE <<XXXX
(* $SML_BASE
 *
 * !!!!! Warning: this file was generated from $CSS_FILE; do not edit !!!!!
 *)

structure CSSStyle =
  struct

    val style = HTML4.Head_STYLE([], [HTML4.PCDATA "\\
XXXX

sed -e "s/.*/          \\\\&\\\\n\\\\/" -e s/\\\"/\\\\\"/g < $CSS_FILE >> $SML_FILE

cat - >> $SML_FILE <<XXXX
          \\"])

  end
XXXX

exit 0
